### ISSUE TITLE
[DEP0091] DeprecationWarning: crypto

### ISSUE THREAD

**Issue by veeramarni** [sysgears/larix#12]
Seeing some `Deprecation` warning from `crypto` library used [here](https://github.com/sysgears/larix/blob/f9ae45eb698d7362120b0c8d21807af11e993fe7/packages/zen/src/executor.ts#L4). 

There are few fixes to get rid of this warnings as per this note. https://github.com/nodejs/node/issues/23203#issuecomment-502459735

**Comment by larixer** [comment]
@veeramarni I don't see this warning, would you be interested to submit a PR?

**Comment by veeramarni** [comment]
@larixer sure will take a look.
