### ISSUE TITLE
I cannot figure out how to create aliases with Zen & Typescript

### ISSUE THREAD

**Issue by alienfacepalm** [sysgears/larix#2]
Is it possible to build a config for a TS project that uses path aliases? I'd like to alias package paths in a monorepo. I can't seem to get this to work after spending days trying everything I can think of. All I could think of was to open an issue, maybe someone can recommend something? Thank you.

**Comment by vlasenko** [comment]
@alienfacepalm I think to support TS paths something like this plugin should be used:
https://github.com/dividab/tsconfig-paths-webpack-plugin

**Comment by alienfacepalm** [comment]
Sick thanks man!

**Comment by alienfacepalm** [comment]
Just to confirm, zen should scan the package.json for this dep and automatically add it?

**Comment by vlasenko** [comment]
@alienfacepalm Well, I am going to add this behavior soon, it will scan package.json for this dep and add it to generated webpack config. But for now, you can add this plugin in your `.zenrc.js` -> `config -> options -> webpackConfig`

**Comment by alienfacepalm** [comment]
So stumped again, not sure where to put the custom webpack config since Zen is generating everything else. Do I put a .zenrc.js at the root of the monorepo or within each package? Sorry if I'm being dense. 

```

const { TsConfigPathsPlugin } = require('awesome-typescript-loader');

resolve: {
    plugins: [
        new TsConfigPathsPlugin(/* { tsconfig, compiler } */)
    ]
}
```

**Comment by alienfacepalm** [comment]
Yeah I figured, still getting `zen error TypeError: Cannot read property 'vendor' of undefined`

with config

```
const TsConfigPathsPlugin = require('tsconfig-paths-webpack-plugin')

const config = {
  builders: {
    core: {
      stack: ['web', 'react'],
      entry: './src/index.ts',
      webpackConfig: {
        plugins: [new TsConfigPathsPlugin()]
      }
    }
  }
}

module.exports = config
```

I'll keep hacking to try to workaround.

**Comment by vlasenko** [comment]
@alienfacepalm If you entry is inside `src/index.tsx`. use `entry: './src/index.tsx'`, exactly like this, because if your entry do not strat with a dot, webpack will search it inside `node_modules`

**Comment by alienfacepalm** [comment]
Yeah I tried all that, `vendor` error each time. I went into the executor and tried to figure out why, but didn't get very far. I'll keep trying.

**Comment by vlasenko** [comment]
@alienfacepalm I will be able to help you quickly if you set up repo on GitHub which reproduces the problem

**Comment by alienfacepalm** [comment]
Ok, I did a new `create-apollo-app`, changed spin to zen and it does the same thing here. https://github.com/alienfacepalm/vendorbug

**Comment by vlasenko** [comment]
@alienfacepalm Thanks, looking....

**Comment by vlasenko** [comment]
@alienfacepalm The quick solution is to drop `builders` key from your `.zenrc.js`. Do you really need to do per-builder config, if not, just drop builders and let zen populate them itself

**Comment by vlasenko** [comment]
@alienfacepalm If you have builders section, right now zen expects that stack property correctly filled in. So the other way to fix it, is to fill in stack in your builders -> web, e.g.:
```
      stack: ['web',
           'es6',
           'js',
           'ts',
           'apollo',
           'react',
           'css',
           'sass',
           'less',
           'webpack'],
```

**Comment by vlasenko** [comment]
@alienfacepalm What I can do to make this simpler - is to ignore `stack` in zen completely and let `zen` fill it in, in any case...

**Comment by alienfacepalm** [comment]
My main reason to use the .zenrc.js is to do some custom webpackConfig like aliases. OK I'll try all this. I use storybook too, but could only get it working with it's own webpack.config.js file, which is fine, but I noticed zen supports it, but I couldn't get it to work by adding to the stack. Thanks man.

**Comment by vlasenko** [comment]
@alienfacepalm There is a storybook integration example in the docs:
https://github.com/sysgears/larix/blob/master/packages/zen/docs/programmatic.md

**Comment by vlasenko** [comment]
@alienfacepalm You are having 404 because you have instructed zen, that your app is rendered on server `ssr: true`, set `ssr: false`, because your server code is not doing server side rendering now.

**Comment by vlasenko** [comment]
@alienfacepalm I had also have to upgrade `apollo-server-express`, because one of its dependencies requires old version of core-js, which looks like as a bug to me, e.g. from the root dir execute:
`yarn workspace tofail-server add apollo-server-express`

**Comment by alienfacepalm** [comment]
Yeah I figured that out, thanks. It's all running as long as I use the long list in stack. Thank you very much.

**Comment by vlasenko** [comment]
@alienfacepalm I'm working on better error messages for this situation and on the feature that you will be able to omit stack in the builders and stack will be autodetected in this case. Improvements will make into @larix/zen@0.1.5 soon

**Comment by alienfacepalm** [comment]
Wow sweet. I had our devops switch us over to Zen, super impressive ease of use.

**Comment by vlasenko** [comment]
@alienfacepalm I have added stack-autodetect feature into `@larix/zen@0.1.7` as well as more user-friendly errors for this case, that should help you recover from situations like this much faster
