### ISSUE TITLE
Cannot read property 'vendor' of undefined

### ISSUE THREAD

**Issue by alienfacepalm** [sysgears/larix#3]
I cannot seem to get .zenrc.js to work. It works great without it, but I need to do some customization, I can't get past this. It's probably something simple, but I figured I'd ask at the risk of looking like a dummy. Thanks a lot for any help. Zen is awesome.

Basic config within web package. 
```

const config = {
  builders: {
    web: {
      stack: ['web'],
      openBrowser: true
    }
  },
  options: {
    ssr: true,
    webpackDll: true,
    reactHotLoader: true,
    webpackConfig: {
      devServer: {
        disableHostCheck: true
      }
    }
  }
}

module.exports = config

```
![error1](https://user-images.githubusercontent.com/9330288/54563275-00d64b00-4986-11e9-92fa-abf649439008.PNG)

**Comment by vlasenko** [comment]
@alienfacepalm Thank you for reporting this issue. It is difficult to start investigation without exact reproduction steps. But I have managed to reproduce issue similar to this, by running the command:
`yarn create @larix my-app@web-rest`
and then putting this config into `.zenrc.js`:
```
const config = {
  builders: {
    'my-app': {
      stack: ['web'],
      openBrowser: true
    }
  },
  options: {
    ssr: true,
    webpackDll: true,
    reactHotLoader: true,
    webpackConfig: {
      devServer: {
        disableHostCheck: true
      }
    }
  }
}

module.exports = config
```
and then running `yarn start` gives the following error:
```
    at /Users/victor/work/my-app/node_modules/@larix/zen/src/executor.ts:732:96
    at new Promise (<anonymous>)
    at buildDll (/Users/victor/work/my-app/node_modules/@larix/zen/src/executor.ts:723:10)
    at runBuilder (/Users/victor/work/my-app/node_modules/@larix/zen/src/executor.ts:1055:56)
    at Object.execute (/Users/victor/work/my-app/node_modules/@larix/zen/src/executor.ts:1185:5)
    at Object.<anonymous> (/Users/victor/work/my-app/node_modules/@larix/zen/src/cli.ts:72:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

**Comment by vlasenko** [comment]
@alienfacepalm So, yeah, it is certainly bug in zen and I'm going to make several measures to close the problems like this. But for now, to unblock you, you can add entry key into config, e.g.:
```
const config = {
  builders: {
    'my-app': {
      stack: ['web'],
      entry: './src/index.ts',
      openBrowser: true
    }
  },
  options: {
    ssr: true,
    webpackDll: true,
    reactHotLoader: true,
    webpackConfig: {
      devServer: {
        disableHostCheck: true
      }
    }
  }
}

module.exports = config;
```

**Comment by alienfacepalm** [comment]
Excellent, thanks man.

**Comment by vlasenko** [comment]
@alienfacepalm Can you create on GitHub some similar project to yours that reproduces the issue, so that I can investigate it? In any case, I'm going to fix this bug and add more troubleshooting tools into this project during next few days

**Comment by vlasenko** [comment]
@alienfacepalm Btw, there is one troubleshooting technique that is already available inside zen: you can launch it with `-v` flag, it will show you first `.zenrc.js` config it uses and then shows you the `webpack` config it has generated. So for example you can move out `.zenrc.js` config first, then launch `zen -v start` to see what `.zenrc.js` it uses by default, it might give you some clues

**Comment by alienfacepalm** [comment]
Ahh, I used create-apollo-app so my entry is index.tsx, but it looks like zen assumes index.ts, so I should have this sorted out soon. :)

  entry: { index: [ 'webpack/hot/signal.js', './src/index.ts' ] },

**Comment by alienfacepalm** [comment]
It's interesting, I got it to work by passing the bigass array for the stack, so the vendor error doesn't show up. But I get a 404 for the client now....cranking away. 


```
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin')

const config = {
  builders: {
    web: {
      stack: ['web', 'es5', 'js', 'ts', 'apollo', 'react', 'css', 'sass', 'webpack'],
      openBrowser: true,
      entry: './src/index.tsx'
    }
  },
  options: {
    ssr: true,
    webpackDll: true,
    reactHotLoader: true,
    webpackConfig: {
      resolve: {
        plugins: [new TsconfigPathsPlugin()]
      },
      devServer: {
        disableHostCheck: true
      }
    }
  }
}

module.exports = config
```
