### ISSUE TITLE
Awesome-typescript-loader breaks

### ISSUE THREAD

**Issue by alienfacepalm** [sysgears/larix#4]
`ts-loader` works fine, but I wanted to move to `awesome-typescript-loader` as from what I've read it does paths better??? Anyways, I get this now. Lots of stuff in Google on this, but so far no luck. I removed `ts-loader` from manifest to possibly stop conflicts, but no luck there either. :)

```
$ zen watch -v
TypeError: Cannot read property 'parentCompilation' of undefined
    at Object.getRootCompiler (Q:\PROJECTS\NOWSECURE\distillery\node_modules\awesome-typescript-loader\src\instance.ts:71:15)
```

**Comment by alienfacepalm** [comment]
OK, I removed my custom zenrc.js files and it works fine so it's a config issue, my bad.

**Comment by alienfacepalm** [comment]
OK, so to reproduce, add awesome-typescript-loader as a dep. Add a .zenrc.js and add a plugin. Take out the plugin object and it works. Also tried `plugins` at top level instead of within `resolve` to same effect. 

```
const path = require('path')
const loader = require('awesome-typescript-loader')
const TsConfigPathsPlugin = require('awesome-typescript-loader')

const config = {
  builders: {
    web: {
      stack: ['web', 'es5', 'js', 'ts', 'apollo', 'react', 'css', 'sass', 'we--bpack'],
      openBrowser: true,
      entry: './src/index.tsx'
    }
  },
  options: {
    ssr: false,
    webpackDll: true,
    reactHotLoader: true,
    webpackConfig: {
      resolve: {
        plugins: [new TsConfigPathsPlugin()]
      },
      devServer: {
        disableHostCheck: true
      }
    }
  }
}

module.exports = config
```

**Comment by vlasenko** [comment]
@alienfacepalm Why did you close issue?

**Comment by alienfacepalm** [comment]
It was a config problem, so it was my fault, I was able to get it to work, there's no bug.
